### PR TITLE
Stats reimplementation

### PR DESCRIPTION
**Pull request by kosecki123**
There is a need for more elastic and rich stats for TimeNodes. The current implementation was based on static counters for bounties and costs, while this is OK for getting these numbers on the screen, it started to be not efficient to expand stats with new features.

The new design will be based on inserting/selecting actions like Discover / Claim / Execute with possible outcomes.

This should allow us to build more informative stats for TimeNodes in CLI and DApp.

### CODE REVIEW

**Comment by kosecki123** [comment]
So initial implementation is done, it does expose 3 methods 

* `discovered`
* `claimed`
* `executed` 

to store new entries. And 

* `getDiscovered`
* `getFailedClaims` / `getSuccessfulClaims`
* `getFailedExecutions` / `getSuccessfulExecutions`

**Comment by Bagaric** [comment]
Also, is there a reason for removing `resetStats`?

**Comment by kosecki123** [comment]
Missing `clear` and `clearAll` added. More tests as suggested by @Bagaric

**Comment by kosecki123** [comment]
I'm gonna keep this open until get it working with CLI and DApp.

**Comment by Bagaric** [comment]
I'll rebase https://github.com/ethereum-alarm-clock/cli/pull/106 to match these changes.

**Comment by kosecki123** [comment]
Added `totalCost` and `totalBounties` to make integration easier. @Bagaric

**Comment by kosecki123** [comment]
@Bagaric all good

**Pull request merged**
