### PR TITLE
[FIX] Stats persistence

### PR DESCRIPTION
**Pull request by Bagaric**
Fixes an issue where stats are bound to `this.stats` and not to the `this.db` object which interferes with LokiJS persistence adapters.

### CODE REVIEW

**Comment by adibas03** [comment]
@Bagaric Looks like only one claim test is failing

**Comment by kosecki123** [comment]
> @Bagaric Looks like only one claim test is failing

TypeError: found.costs.plus is not a function

Is found.costs of BigNumber type?

**Comment by Bagaric** [comment]
@kosecki123 It is. Where do you get that error?

**Comment by kosecki123** [comment]
This is from https://travis-ci.org/ethereum-alarm-clock/timenode-core/jobs/416135505 from unit test

**Pull request merged**
